version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - serverless package
      - serverless deploy

# THIS CONFIG IS IF WE WANT TO SEND THE FILES TO AN ARTIFACT
#artifacts:
#  files:
#    - '**/*'
#  discard-paths: yes
#  base-directory: 'dist/angular-skeleton'
